import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { Session } from '@supabase/supabase-js';
import { supabase } from '../utils/supabaseClient';
import { Auth } from '../components/Auth';
import { Dashboard } from '../components/Dashboard'

const Home: NextPage = () => {
  const [session, setSession] = useState<Session | null>();

  useEffect(() => {
    setSession(supabase.auth.session());

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
    })
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {!session ? <Auth /> : <Dashboard session={session} />}
        </div>
      </main>
    </div>
  )
}

export default Home
